version: "3.1"
services:
    database:
        restart: always
        image: postgres

    web:
        restart: always
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/transparentCDN_app/transparentAPP:/code
            - ./html:/var/www/website/html
            - ./transparentCDN_app/transparentAPP/templates:/var/www/website/transparentAPP/templates
        ports:
            - "8000:8000"
        depends_on: 
            - database
