version: "3.1"
services:
    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=demo
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        ports:
            - "8002:3306"
    web:
        restart: always
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/transparentAPP:/code
            - ./transparentAPP/templates:/var/www/website/transparentAPP/templates
        ports:
            - "8000:8000"
        depends_on: 
            - mysql
